name: Build Android & iOS

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
 build-android:
    needs: install-and-test
    uses: ./.github/workflows/android-build.yml
    with:
      environment: release
    secrets: inherit