---
####################
####################
## Auto Formatter ##
####################
####################
name: Formate Code

#
# Documentation:
# https://github.com/mezgoodle/auto-formatter
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: 
     - main

# Set the Job #
jobs:
  build:
    # Name the Job
    name: Formate Code
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps #
    steps:
      # Checkout the code base #
      - name: Checkout Code
        run: yarn https://github.com/mezgoodle/auto-formatter