name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install npm dependencies
        run: yarn install

      - name: Code Formatting
        run: yarn "prettier --write ."
