name: Build & upload to Firebase App Distribution 

on:
 push:
  branches:
    - upload_to_firebase

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    - name: Install Node modules
      run: yarn ci
    - name: clean build folder 
      run: cd android && ./gradlew clean && cd ..
    - name: build release 
      run: cd android && ./gradlew assembleRelease && cd ..
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: '1:569228925032:android:ae7d8331ae02c49301c3dd'
        token: '1//0gP9B1vpyaCbLCgYIARAAGBASNwF-L9IrH-WekGG_9ZrZYFlH8a6rGreOAP9YWxmklmJkyWq36izhouRhO3nbdmkw6CSE4ADqFac'
        groups: testers
        file: app/build/outputs/apk/release/app-release.apk